[supervisord]
nodaemon=true
user=mongodb
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid

[program:cfgsvr]
command=mongod --configsvr --replSet=cfgRS --port=27019 --bind_ip_all --dbpath=/data/cfg --wiredTigerCacheSizeGB=0.25 --journalCommitInterval=100
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:shard1]
command=mongod --shardsvr --replSet=shard1 --port=27018 --bind_ip_all --dbpath=/data/shard1 --wiredTigerCacheSizeGB=1.0 --journalCommitInterval=100
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:mongos]
command=mongos --configdb=cfgRS/localhost:27019 --port=27017 --bind_ip_all
priority=30
autostart=true
autorestart=true
startsecs=15
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
